.travis.yml
Here u go @amcdnl.
As mentioned, this is a first version that needs to be tested with Travis. The `branches` only master is for the semantic-release hook we add in later.
=> Add Travis Config

config/spec-bundle.js, package.json, src/common/charts/chart.component.spec.ts, src/common/legend.component.spec.ts, src/tree-map/tree-map-cell-series.component.ts
Ok, so this PR should complete the upgrade to RC.6
=> Upgrade rc6

package.json
Allows for easier use with typescript - the compiler automatically picks up the definitions.
=> Add typings entry to package.json

src/area-chart/area-chart.module.ts, src/bar-chart/bar-chart.module.ts, src/common/chart-common.module.ts, src/common/charts/chart.component.spec.ts, src/common/legend.component.spec.ts, src/force-directed-graph/force-directed-graph.module.ts, src/gauge/gauge.module.ts, src/heat-map/heat-map.module.ts, src/index.ts, src/line-chart/line-chart.module.ts, src/ng2d3.module.ts, src/number-card/number-card.module.ts, src/pie-chart/pie-chart.module.ts, src/tree-map/tree-map.module.ts
The project owner should rebuild package/release routines to incorporate changes from updated source when release new version.
This commit renames occurrences of CommonModule to ChartCommonModule to avoid
name conflicts with @angular/common class of the same name.
The submitted changes  do not include build artefacts from release/ directory
and building these artefacts is up to main project maintainers (I am
quite unaware how this project is release at the moment).
Thanks!
=> Rename CommonModule to ChartCommonModule. Closes #109

demo/index.html
The 3rd party scripts block rendering of demo content page. The layout for share buttons could be a little better
- asynchronous deffered loading for 3rd party scripts
- Flex based layout
Optimize rendering and layout of social links bar
This commit optimize rendering and layout for social links
rendered on the top of the page:
- make sure that 3rd party scripts do not block rendering and are downloaded
asynchronously as the non important content
- use HTTPS only links
- optimize layout for top links using Flex CSS layout. Just wrap into container
and …
=> Optimize rendering of top sharing buttons

src/common/base-chart.component.ts, src/common/chart-common.module.ts, src/common/rxjs-extensions.ts
But please review this PR on compatibility with existing RxJS implementation and expected results.
This commit optimizes use of RxJS by using explicit imports statements only
for used operations and static class methods.
The implementation follows John Papa`s solution used in NG2 Tour of Heroes:
https://git.io/v14aZ
also documented in the official NG2 documentation:
https://goo.gl/Bl7WyD
The added `rxjs-extensions` file contains all imports for static methods
and used operators. The existing code has been modified to use explicit
import statement for Observable.
The commit has been tested locally using demo application with …
=> Add RxJS imports for operators and methods. Closes #62

src/ng2d3.scss
https://github.com/swimlane/ng2d3/issues/106
The outline was removed
- Remove Default Browser Outline on click
=> Fix for bug #106

demo/app.component.ts, demo/chartTypes.ts, src/gauge/gauge.component.ts
- [ X] Feature
We can't set our own margins
I only modify the gauge charts (for my need) to allow margin overriding.
I can do the same for other graphs if you think it is useful.
=> Add margin support for Gauge charts

demo/app.component.ts
Artifact shown in demo page.
Artifact removed.
=> fix(demo): fix artifact in demo page

docs/charts/bar-horizontal-2d.md, docs/charts/bar-horizontal-normalized.md, docs/charts/bar-horizontal-stacked.md, docs/charts/bar-horizontal.md, docs/charts/bar-vertical-2d.md, docs/charts/bar-vertical-normalized.md, docs/charts/bar-vertical-stacked.md, docs/charts/bar-vertical.md, src/bar-chart/bar-horizontal-2d.component.ts, src/bar-chart/bar-horizontal-normalized.component.ts, src/bar-chart/bar-horizontal-stacked.component.ts, src/bar-chart/bar-horizontal.component.ts, src/bar-chart/bar-vertical-2d.component.ts, src/bar-chart/bar-vertical-normalized.component.ts, src/bar-chart/bar-vertical-stacked.component.ts, src/bar-chart/bar-vertical.component.ts
Axis tick formatting cannot be specified for bar charts.
Axis tick formatting can now be specified for bar charts.
=> feat(charts): add axisTickformatting inputs to bar charts

src/gauge/gauge-axis.component.ts, src/gauge/gauge.component.ts
Decimals are not displayed in gauge axis tick marks.
Decimals are now displayed in gauge axis tick marks.
=> fix(gauge-axis): fix axis number formatting, Fix #122

src/heat-map/heat-map.component.spec.ts
Adds tests.
Refactoring heat-map test
=> chore(heat-map): cleaning heatmap test

package.json
=> chore(ci): add linting to test script for ci

package.json, src/bar-chart/series-horizontal.component.ts, src/bar-chart/series-vertical.component.ts, src/common/color.helper.ts, src/common/grid-layout.helper.ts, src/common/legend/advanced-legend.component.ts, src/gauge/gauge.component.ts, src/pie-chart/pie-grid.component.ts, src/tree-map/tree-map.component.ts
=> Fix linting and extract-text-webpack-plugin issue.

demo/app.component.html, demo/app.component.scss, demo/app.component.ts
Adds the current version to the demo pages.
=> chore(demo): add version to demo page

demo/app.component.ts
Bugfix
Real-time in demo is not updated in line/area charts
Real-time in demo is now updated in line/area charts
=> fix(demo): Fix #87

src/bubble-chart/bubble-series.component.ts
Values not shown when y=0
All values shown unless x or y are undefined.
=> fix(bubble-chart): Fix values not shown when y=0

config/helpers.js, config/webpack.common.js, src/bubble-chart/bubble-chart.component.spec.ts, src/declarations.d.ts, src/heat-map/heat-map.component.spec.ts
CI related changes
Some tests are disabled because they inexplicably fail on Travis.
Tests are only disabled on Travis.
No
=> Testing disabling tests on travis

src/bar-chart/bar-vertical-stacked.component.ts, src/common/tick-format.helper.ts, src/heat-map/heat-map.component.ts, src/pie-chart/pie-label.component.ts
Several lint errors from a fresh checkout and `npm install`.
No lint errors.
=> fix: correct lint errors

package.json
Update to test-related development dependency.
peer dependency warning caused by outdated version of `codelyzer`.
removes a peer dependency warning between `codelyzer` and `tslint`
=> test: bump codelyzer version to latest stable

package.json
Several unnecessary Angular related peer dependencies included.
RxJS version is also pinned.
Following peer dependencies were removed as they are not directly used:
* `@angular/compiler`
* `@angular/platform-browser`
* `@angular/platform-browser-dynamic`
* `core-js`
* `zone.js`
RxJS was unpinned to match the version methodology of Angular 2.4.5+
=> refactor: simplify angular peer dependencies

src/common/count/count.directive.ts
Charts using this directive don't work in AOT mode.
Charts using this directive work in AOT mode.
=> fix(count): work in aot mode

demo/app.component.html, docs/charts/number-card.md, src/common/grid-layout.helper.ts, src/number-card/card-series.component.ts, src/number-card/card.component.scss, src/number-card/card.component.ts, src/number-card/number-card.component.ts
Feature
Number cards are too bold.
Number cards now can be set to only display a bar for the color scale.
No
=> feature(number-crads): improved number card design and scaling

config/webpack.test.js, tsconfig.spec.json
Tests are failing.
Tests now pass.  A separate tsconfig for unit tests has also been created.
=> test: correct and split tsconfig for specs

src/bar-chart/bar-horizontal-2d.component.ts, src/bar-chart/bar-horizontal-normalized.component.ts, src/bar-chart/bar-horizontal-stacked.component.ts, src/bar-chart/bar-vertical-2d.component.ts, src/bar-chart/bar-vertical-normalized.component.ts, src/bar-chart/bar-vertical-stacked.component.ts, src/bubble-chart/bubble-chart.component.ts, src/force-directed-graph/force-directed-graph.component.ts, src/gauge/gauge-axis.component.ts, src/heat-map/heat-map.component.ts, src/pie-chart/advanced-pie-chart.component.ts, src/pie-chart/pie-label.component.ts
In 4.3.0 version ng compiler raises errors (#274) when compiling ngx-charts in different project as a library.
Errors are introduced in templates - misuse of bindings and wrong signature calls.
no errors
=> fix: aot errors (#274)

demo/app.component.ts, demo/chartTypes.ts
=> fix(demos): calendar demo

demo/app.component.ts
Feature (demo)
Changing the chart type will update the URL,  usefull for testing and deep linking.
No
=> feat(demo): simple deep linking

.gitignore, .vscode/settings.json
**What kind of change does this PR introduce?**
Other
=> chore: Update .gitignore

demo/app.component.html, demo/app.component.ts, demo/chartTypes.ts, docs/charts/number-card.md, src/number-card/card-series.component.ts, src/number-card/card.component.ts, src/number-card/number-card.component.ts
Feature
Number cards always display numbers.
valueFormatting input to number card chart allow formatting of the value.
No
=> feat(number-card): add valueFormatting input to number card chart

demo/app.component.html, demo/app.component.scss, demo/app.component.ts, src/number-card/card-series.component.ts, src/number-card/card.component.ts, src/number-card/number-card.component.ts
Feature
Adds `labelFormatting` input.
No
=> feat(number-cards): add label formatting input

demo/app.component.html, src/number-card/card-series.component.ts
=> fix(number-charts): add default value for label format

src/number-card/card.component.ts
=> fix(number-cards): add zone.run to number-cards update

demo/app.component.html, demo/app.component.ts, demo/app.module.ts, demo/data.ts, package.json, src/bubble-chart/bubble-series.component.ts, src/common/grid-layout.helper.ts, src/number-card/card.component.ts
Bugfix and Demo
- Axis labels in demo for bubble chart are wrong.
- Missing series or point name results in ugly tooltip.
- Axis labels in demo for bubble chart are fixed.
- Missing series or point name results in decent tool tips.
No
=> Bubble chart fixes

src/common/base-chart.component.ts, src/common/view-dimensions.helper.ts
Bugfix
Dimension rounding causes wrong placement of the legend
Dimensions are truncated instead of rounded.
No
=> fix: trauncate to get integers, fixes #360

demo/app.component.html, demo/chartTypes.ts, docs/charts/tree-map.md, src/tree-map/tree-map-cell-series.component.ts, src/tree-map/tree-map-cell.component.ts, src/tree-map/tree-map.component.ts
Feature
Adds gradiants to tree-map cells.
No
=> feature(tree-maps): add gradiant

src/number-card/card-series.component.ts, src/number-card/card.component.ts
Bugfix
Count animation not working when valueFormatting function not supplied.
Count animation now working.
No
=> fix(number-cards): fix value animation

demo/app.component.html, demo/app.component.ts, docs/charts/tree-map.md, src/common/count/count.directive.ts, src/tree-map/tree-map-cell-series.component.ts, src/tree-map/tree-map-cell.component.ts, src/tree-map/tree-map.component.ts
Feature
Add value and label formatting
No
=> feature(tree-map): add value and label formatting

demo/app.component.html, demo/app.component.scss, demo/app.component.ts, demo/chartTypes.ts, demo/data.ts
Demo
Adds an interactive demo for treemap chart.
No
=> Add interactive treemap demo

docs/contributing/community.md
=> docs(community): corrected company name

LICENSE.md
=> add LICENSE.md, fixes #436

src/common/legend/legend.component.scss
[Issue #486 ](https://github.com/swimlane/ngx-charts/issues/486)
Long text in legend now ends with an ellipsis before being cut off.
=> Legend text

src/polar-chart/polar-chart.component.ts
There's a typo in the polar-chart component.
Typo is fixed.
=> fix(polar): Fixed a typo

src/common/tooltip/injection.service.ts
tooltip injection service
Error: cannot read length of undefined
No error
=> fix cannot read length of undefined.

demo/app.component.scss, docs/changelog.md, src/common/legend/advanced-legend.component.scss, src/common/legend/legend.component.scss, src/common/legend/legend.component.ts, src/number-card/card.component.scss, src/number-card/card.component.ts, src/pie-chart/pie-label.component.ts
=> Updated styles to improve legibility

src/pie-chart/pie-grid.component.ts
#679 
Display only one '%' in the pie grid
=> delete the % from svg:text *ngIf=animation

src/common/circle-series.component.ts
No typing of colors property
Typing of colors property
**Other info**
In general I believe the charts typing could be done better (e.g. for expected format of the chart data). Here is an improvement for the colors property.
=> Fix typing of colors property

src/common/axes/axis-label.component.ts
=> Remove duplicate code

src/common/color.helper.ts
(#676)
BaseChartComponent has a property named "customColors". Bound values are passed to ColorHelper. This expects an array with mapping entries (name -> color).
ColorHelper now checks if customColors is a function. In this case the function is called and the result is returned as color. It is now possible to fill e.g. TreeMap cells with individual colors. …
=>  Binding functions to customColors to set individual colors for cells (#676)

src/common/tooltip/tooltip.component.ts, src/pie-chart/pie-grid-series.component.ts
The build fails with `fullTemplateTypeCheck` when used in projects with `AngularCompilerPlugin`
It passes
na
Closes #711
=> Fix template compile errors with fullTemplateTypeCheck

demo/app.component.html, demo/app.component.ts, demo/chartTypes.ts, demo/data.ts, src/bar-chart/bar-horizontal-stacked.component.ts, src/bar-chart/bar-vertical-stacked.component.ts, src/bar-chart/series-horizontal.component.ts, src/bar-chart/series-vertical.component.ts
https://github.com/swimlane/ngx-charts/issues/233
=> Issue(233) stacked bar chart negative values issue

src/area-chart/area-chart.component.spec.ts
No current test for area-chart, just a very basic test I created to have some experience with this library.
Tests if area-chart is created correctly, and has much area-paths as series provided.
=> Added basic test of area-chart

demo/app.component.html, demo/app.component.ts, demo/chartTypes.ts, src/heat-map/heat-map.component.ts
- [x ] Bugfix
- [x ] Refactoring (no functional changes, no api changes)
unused import fails CI check https://github.com/swimlane/ngx-charts/pull/877
removed the unused import
=> Unused import removed from 7.0.x branch

src/area-chart/area-chart.component.spec.ts
Not testing on colors.
Testing on colors.
Want to spend some more time on this library, as I think it deserves some more attention.
Will try to get something in, that contains a functionality or performance improvement later this month.
#hacktoberfest
=> Added 1 extra test for area-chart

docs/examples/line-area-charts/line-chart.md
- [ x] Other... Please describe:
doc fix
- [ x] No
=> fix value typo

src/area-chart/area-chart-normalized.component.ts, src/area-chart/area-chart-stacked.component.ts, src/area-chart/area-chart.component.spec.ts, src/area-chart/area-chart.component.ts, src/bubble-chart/bubble-chart.component.ts, src/bubble-chart/bubble-chart.utils.ts, src/common/domain.helper.ts, src/heat-map/heat-map.component.ts, src/line-chart/line-chart.component.ts, src/polar-chart/polar-chart.component.ts
If you have feedback (always welcome) then I can add a commit to this PR as well.
EDIT: woops, I branched too late. I guess that will be fixed when that PR gets in, otherwise I rebranch this.
-------------------------------------------
It walks over the whole array twice.
> .every() method executes the provided callback function once for each element present in the array until it finds one where callback returns a falsy value.
Will be much faster, but only noticable with larger charts. I didn't do a analysis, but I guess this is an improvement anyway. (I could do some testing or set up a jsperf if you are …
=> getScaleType performance improvement

src/common/tooltip-area.component.ts, src/common/tooltip/tooltip.component.ts, src/common/tooltip/tooltip.directive.ts, tslint.json
Enabled tslint deprecation warning, and migrated to Renderer2, with angular recommendations.
Followed recommend alternatives.
Using deprecated Renderer.
Using Renderer2.
=> Migrated to Renderer2

docs/changelog.md
Fix documentation typo on docs/changelog.md
Feathre
Fixex 
servoce 
gradiant 
highight 
objets 
Feature
Fixed 
service 
gradient 
highlight 
objects 
=> fix documentation typo

docs/contributing/building.md
At https://swimlane.gitbook.io/ngx-charts/contributing/building page the link address referring to **npm tasks** is outdated.
The **npm tasks** link is updated.
=> Update npm tasks link address.

src/pie-chart/pie-arc.component.ts
Hey all! Starting the New Year off right! 🎉
Pie Chart intermittently flickers on Safari. Tested and reproduced on OS X El Capitan > Safari 10 and iPhone X iOS 12
_(Slowed for gif recorder to capture flicker)_
Pie Chart now animates smoothly on Safari. 
=> (fix): Pie Chart flicker on Safari

docs/motivation.md
=> [motivation.md] Typo fix

docs/motivation.md
The link custom charts was formatted wrong and not working.
- [ x ] Other... Please describe:
The link to custom charts doesn't work.
The link works.
- [ x ] No
-
=> Fix link typo in motivation.md

.travis.yml, config/webpack.common.js, config/webpack.dev.js, config/webpack.test.js, package.json
AOT build with webpack 3+ fails
the build doesn't fail
=> bump extract-text-plugin to version 3.0.2

demo/app.component.html, demo/app.component.ts, demo/chartTypes.ts, docs/examples/gauge-chart.md, src/gauge/gauge.component.ts
Resolves conflicts for https://github.com/swimlane/ngx-charts/issues/230
=> Add option to remove text from Gauge Chart

src/pie-chart/index.ts
the build fails with ivy #1168
The build runs successfully
=> add missing export

package-lock.json, package.json
https://github.com/swimlane/ngx-charts/issues/1186
=> update zone.js version to 0.9.1

src/heat-map/heat-map.component.ts, src/pie-chart/advanced-pie-chart.component.ts
=> Pass the correct number of parameters to fix production build

demo/app.component.ts, src/bar-chart/series-horizontal.component.ts, src/bar-chart/series-vertical.component.ts, src/bubble-chart/bubble-series.component.ts, src/common/circle-series.component.ts, src/common/label.helper.ts, src/force-directed-graph/force-directed-graph.component.ts, src/gauge/gauge-arc.component.ts, src/heat-map/heat-map-cell-series.component.ts, src/number-card/card.component.ts, src/pie-chart/pie-series.component.ts, src/polar-chart/polar-series.component.ts, src/tree-map/tree-map-cell-series.component.ts, src/tree-map/tree-map-cell.component.ts
#1137 
Tooltip labels of the barchart is not escaped.
Tooltip labels of the barchart is escaped.
=> Sanitize tooltip labels

projects/swimlane/ngx-charts/src/lib/common/tooltip/injection.service.ts
=> Allow view container injection

docs/changelog.md
Currently there are a few spelling errors within the changelog (which I think come from the original PR titles).
I ran a spellchecker over the code & corrected the ones which had fairly clear correct spelling.
=> Refactor: correcting a few spelling errors in changelog

package-lock.json, projects/swimlane/ngx-charts/src/lib/common/legend/scale-legend.component.ts
Closes #1551
Removed unnecessary call to bypassSecurityTrustStyle in scale-legend component
While I couldn't find any way that this call could be exploited, while testing it proved it is no longer necessary, so I'm removing it.
=> Remove bypassSecurityTrustStyle call

.github/workflows/test_and_deploy.yml, angular.json
=> Remove maximumError in angular budgets

projects/swimlane/ngx-charts/src/lib/common/base-chart.component.ts, projects/swimlane/ngx-charts/src/lib/number-card/card.component.ts
=> Disable animation on ssr and remove unnecesary call on ssr

projects/swimlane/ngx-charts/src/lib/common/timeline/timeline.component.ts, src/app/custom-charts/timeline-filter-bar-chart/timeline-filter-bar-chart.component.ts
Fixes #1575 
Selection in timeline will change x-axis range in the main chart again. 
=> Fixing timeline selection

docs/changelog.md, projects/swimlane/ngx-charts/package.json
=> (release): 18.0.0

README.md, docs/changelog.md, projects/swimlane/ngx-charts/package.json
=> (release): 18.0.1

docs/changelog.md, projects/swimlane/ngx-charts/package.json
=> (release): 19.0.0

docs/changelog.md, projects/swimlane/ngx-charts/package.json
=> (release): 19.0.1

projects/swimlane/ngx-charts/src/lib/common/base-chart.component.scss, projects/swimlane/ngx-charts/src/lib/common/charts/chart.component.ts
Using an angular animation for the fade in in the main chart component is causing an error in SSR: `cannot read display of undefined`
The fade in animation of the chart is replaced with a CSS transition
=> (fix): change transition to CSS to fix nguniversal error

docs/changelog.md, projects/swimlane/ngx-charts/package.json
=> (release): 19.2.0

.gitignore, angular.json, package-lock.json, package.json, projects/swimlane/ngx-charts/ng-package.json, projects/swimlane/ngx-charts/package.json, projects/swimlane/ngx-charts/src/lib/common/tooltip/tooltip.module.ts, projects/swimlane/ngx-charts/src/test.ts, src/polyfills.ts, src/test.ts
=> Update to Angular 13

docs/changelog.md, projects/swimlane/ngx-charts/src/lib/models/chart-data.model.ts, projects/swimlane/ngx-charts/src/lib/pie-chart/pie-grid-series.component.ts, projects/swimlane/ngx-charts/src/lib/pie-chart/pie-grid.component.ts
=> Fix: cyclic import error

projects/swimlane/ngx-charts/src/lib/bar-chart/bar-horizontal-2d.component.ts, projects/swimlane/ngx-charts/src/lib/bar-chart/bar-horizontal-normalized.component.ts, projects/swimlane/ngx-charts/src/lib/bar-chart/bar-horizontal-stacked.component.ts, projects/swimlane/ngx-charts/src/lib/bar-chart/bar-vertical-2d.component.ts, projects/swimlane/ngx-charts/src/lib/bar-chart/bar-vertical-normalized.component.ts, projects/swimlane/ngx-charts/src/lib/bar-chart/bar-vertical-stacked.component.ts, projects/swimlane/ngx-charts/src/lib/bar-chart/series-vertical.component.ts, projects/swimlane/ngx-charts/src/lib/bubble-chart/bubble-chart.component.ts, projects/swimlane/ngx-charts/src/lib/bubble-chart/bubble-series.component.ts, projects/swimlane/ngx-charts/src/lib/common/circle-series.component.ts, projects/swimlane/ngx-charts/src/lib/line-chart/line-chart.component.ts, projects/swimlane/ngx-charts/src/lib/line-chart/line.component.ts, projects/swimlane/ngx-charts/src/lib/polar-chart/polar-chart.component.ts, src/app/custom-charts/bubble-chart-interactive/bubble-chart-interactive.component.ts
Leave Animations on charts with series are always turned on, even on SSR.
Leave animations are no longer happening on SSR, but continue to be present when on the client/browser
=> Remove angular animations when  SSR on charts with series

docs/changelog.md, projects/swimlane/ngx-charts/package.json
=> (release): 20.1.0

docs/examples/bar-charts/horizontal-bar-chart.md
This was added in https://github.com/swimlane/ngx-charts/pull/408
I just stumbled over this, this is likely also missing in the other examples.
- Docs
=> Add roundEdges

.npmrc, package-lock.json, package.json, projects/swimlane/ngx-charts/ng-package.json, projects/swimlane/ngx-charts/package-lock.json, projects/swimlane/ngx-charts/package.json, projects/swimlane/ngx-charts/src/lib/box-chart/box.component.ts
=> Replace deep clone

docs/changelog.md, projects/swimlane/ngx-charts/package.json
Bump dependency version in library project
=> (release): 20.1.2

docs/changelog.md, projects/swimlane/ngx-charts/src/lib/common/axes/ticks.helper.ts, projects/swimlane/ngx-charts/src/lib/common/axes/x-axis-ticks.component.ts
=> fix: SSR mode avoid label cut off

docs/changelog.md, projects/swimlane/ngx-charts/package.json
=> (release): 20.3.1

.github/workflows/test_and_deploy.yml
GitHub Pages deployment is broken.
Restores command as it should work with `npm run`.
=> Fix Deployment

package.json, yarn.lock
Github Pages deployment is broken.
Upgraded package to get latest and trying again.
=> Github Pages Deployment

projects/swimlane/ngx-charts/src/lib/sankey/sankey.component.ts
Sankey Diagram does not support custom colors.
Sankey Diagram supports custom colors.
=> Sankey Custom Colors

docs/changelog.md, projects/swimlane/ngx-charts/package.json
=> Release 23.0.0-alpha.0
