swimlane/ngx-charts

src/common/axes/axes.module.ts
src/common/common.module.ts
src/common/tooltip/tooltip.module.ts

Apps that are using lazy loading will get errors if the lazy loaded module imports the BrowserModule (or imports NG2D3Module that imports BrowserModule).  I swapped out BrowserModule for CommonModule in all the ng2d3 imports.  The demo still imports BrowserModule, since that's the right place for it.
All the tests still pass, and the demo still works.  I'll look at AoT next.

Use CommonModule instead of BrowserModule in lib

---

demo/app.ts
demo/chartTypes.ts
demo/data.ts
src/d3.ts
src/force-directed-graph/force-directed-graph.component.ts
src/force-directed-graph/force-directed-graph.module.ts
src/ng2d3.ts

Added force-directed-graph
This extends `BaseChart` for the dimension calculations, but doesn't use the `results` property since it doesn't use a series type data structure.
`customColors`, `legend`, `scheme`, and `view`.
- `nodes: any[]` - Nodes in the graph
- `links: { source: any, target: any }[]` - Connects nodes together.  Source and target can be either an object reference or a node id.  See [forceLink().id](https://github.com/d3/d3-force#link_id)
- `force` - *(optional)* Customized d3.forceSimulation. Default:
d3.forceSimulation()
.force("charge", d3.forceManyBody())
.force("collide", d3.forceCollide(5))
.force("x", d3.forceX())
.force("y", d3.forceY());
- `forceLink` - *(optional)* Customized d3.forceLink. Default:  
d3.forceLink().distance(20).strength(1).id(node => node.value); …

Force Directed Graph

---

src/area-chart/area-chart-normalized.component.ts
src/area-chart/area-chart-stacked.component.ts
src/area-chart/area-chart.component.ts
src/common/circle-series.component.ts
src/line-chart/line-chart.component.ts

- fixes swimlane/ngx-charts#149
changes all occurences of `ceries` to `series`

fix(circle-series): ceries typo

---

src/common/axes/x-axis.component.ts
src/common/axes/y-axis.component.ts

- [ x ] Bugfix
Users are unable to specify the tick count for the axis.
Users are able to supply the tick count for axis via an Input.
- [ x ] No

Update Axis components to allow tick count to be an input

---

src/common/base-chart.component.ts

Includes all of RxJS even-though only a small fraction of it was used.
Only the parts of RxJS that are actually used will be included in the production bundle.
Relates to #131
I'm aware that this was attempted before in #116 which ended up being reverted due to problems mentioned in #119. The issue shouldn't occur this time around though since the operators/observable is imported in `base-chart.component.ts`, where it's actually used, as opposed to previous attempt where they were imported in `chart-common.module.ts` which I …

Only include used Rxjs operators to decrease file size

---

src/bubble-chart/bubble-chart.component.ts
src/bubble-chart/bubble-series.component.ts

Feature
Values in bubble tool-tip are cryptic.
Add x and y axis labels to tooltips.
We may want to an an ngIf on each value.  Either on the xAxisLabel or showXAxisLabel.

feat(bubble): show axis labels in tooltip

---

src/bubble-chart/bubble-series.component.ts

Axis labels in tooltips when are shown as `:` when no label is passed.
Hide axis labels in tooltips when none are given

fix(bubble): Hide axis labels in tooltips when none are given

---

demo/app.component.html
demo/app.component.ts
src/gauge/gauge.component.ts

Option to override displayValue with custom textValue
The display value in the Gauge automatically defaults to the results value (input).
Option to override the displayValue with a custom textValue. I would like the flexibility to display a value not equal to the default single value or the sum of the values in the series.
Example: 
- Min value = 0
- Max value = 100
- Arc 1 = Actual = 250
- Arc 2 = Target = 300
- Display Value = 250 .. not 550
If this PR contains a breaking change, please describe the impact and migration path for existing …

feat(gauge): option to override displayValue

---

demo/app.component.html
demo/app.component.ts
demo/chartTypes.ts
src/bubble-chart/bubble-chart.component.ts
src/bubble-chart/bubble-chart.utils.ts

Bugfix
Padding was not added to bubble chart when the scale is ordinal.
Padding was too generous.
Padding was now added to bubble chart with ordinal scales.
Padding was too greedy on each side.
No

Fix padding on bubble charts

---

package.json

When installing package dependencies with `npm install`, newer jasmine typings are installed which cause the following errors during `npm run build`:
> ERROR in [at-loader] node_modules\@types\jasmine\index.d.ts:39:52
>     TS1005: '=' expected.
> 
> ERROR in [at-loader] node_modules\@types\jasmine\index.d.ts:39:38
>     TS2371: A parameter initializer is only allowed in a function or constructor implementation.
> 
> ERROR in [at-loader] node_modules\@types\jasmine\index.d.ts:39:46
>     TS2304: Cannot find name 'keyof'.
Typings are locked to version 2.5.41 which do not have this bug.
**Does this PR introduce a …

fix(build): Lock jasmine typings to avoid errors during build.

---

src/area-chart/area-chart-normalized.component.ts
src/area-chart/area-chart-stacked.component.ts
src/area-chart/area-chart.component.ts
src/bar-chart/bar-horizontal-2d.component.ts
src/bar-chart/bar-horizontal-normalized.component.ts
src/bar-chart/bar-horizontal-stacked.component.ts
src/bar-chart/bar-vertical-2d.component.ts
src/bar-chart/bar-vertical-normalized.component.ts
src/bar-chart/bar-vertical-stacked.component.ts
src/bubble-chart/bubble-chart.component.ts
src/force-directed-graph/force-directed-graph.component.ts
src/line-chart/line-chart.component.ts

`legendLabelClick` calls `onClick` with just one parameter, causing AoT compilation to fail.
The `onClick` functions do actually check if the 2nd parameter is given, so it's clear that the 2nd parameter is intended to be optional.
Fixes: #232
Optional parameters in `onClick` functions have been marked with a questionmark (`?`) to show that they can be omitted. Typescript will then happily compile AOT again.
This PR should fix AOT errors with all chart types. We currently only tested line and bar charts, but we assume that it should work with the others just as fine, since the `onClick` function calls are the same on …

fix(AOT): Mark optional parameters in onClick functions.

---

tsconfig-aot.json

When running rollup to minify code, rollup throws a bunch of 'x is not exported by ...' errors.
Rollup works.
This PR changes the tsconfig-aot module setting from `commonjs` to `es2015`. This change is required, otherwise rollup is not able to detect the modules.
Quote from the [Angular 2 AOT Cookbook](https://angular.io/docs/ts/latest/cookbook/aot-compiler.html#!#tree-shaking):
> Rollup can only Tree Shake ES2015 modules which have import and export statements.
In order for rollup to successfully work, the modules need to be …

fix(rollup): Set tsconfig-aot module to 'es2015'.

---

src/area-chart/area-chart-normalized.component.ts
src/area-chart/area-chart-stacked.component.ts
src/area-chart/area-chart.component.ts
src/bar-chart/bar.component.ts
src/bubble-chart/bubble-series.component.ts
src/common/area.component.ts
src/common/base-chart.component.ts
src/common/circle-series.component.ts
src/common/timeline/timeline.component.ts
src/heat-map/heat-map-cell.component.ts
src/line-chart/line-chart.component.ts
src/line-chart/line-series.component.ts
src/pie-chart/pie-arc.component.ts

Gradients don't work when HashLocationStrategy is used.
Fixes: #238 
`Location` references have been replaced with `LocationStrategy`. This is required for the `instanceof` check against `PathLocationStrategy`. Since `LocationStrategy` has a working `path()` method as well, there should be no problems using it instead of `Location`.
This PR makes sure that `pageUrl` is the current `location.path()` if `PathLocationStrategy` is being used, otherwise it will be an empty string.
Changes tested with Chrome v56 and Firefox v51.
If this PR contains a …

fix(charts): Only prepend pathUrl when PathLocationStrategy is used.

---

package.json

reduces the files installed by the package
A large amount of unneeded files are installed with the package
Only the `release` directory, `package.json`, and the `README` are now included.  Note that the last two are included by default.
If this PR contains a breaking change, please describe the impact and migration path for existing applications: 
The full source as well as build configuration files were previously present.  Some users may have incorrectly referenced these files.  Only the `release` files should be used from within the package. …

fix(packaging): limit package contents to release directory

---

package.json

The peer and development dependency versions of d3 are mismatched.  This results in an npm warning during development.
The peer and development versions are synchronized.  The version is also unpinned as d3 appears to follow a semver approach to its API.

fix: synchronize and unpin the d3 dependency

---

src/bar-chart/bar-horizontal.component.spec.ts
src/bar-chart/bar-vertical.component.spec.ts
src/bubble-chart/bubble-chart.component.spec.ts
src/common/charts/chart.component.spec.ts
src/common/legend/legend.component.spec.ts
src/heat-map/heat-map.component.spec.ts
src/pie-chart/pie-chart.component.spec.ts

Tests currently use the d3 selection API to query for elements and attributes.
DOM query selection as well as built-in Angular helpers are used to query for elements and attributes.

test: replace use of d3 selection api

---

docs/charts/number-card.md
src/number-card/card-series.component.ts
src/number-card/card.component.ts
src/number-card/number-card.component.ts

Feature
Card text is always colored as the inverse of the card color.
User can specify the card color.
No

feature(number-cards): Ability to set card text color, Fixes #282

---

src/line-chart/line-chart.component.ts

Bugfix
Throws an error when `roundDomains` is set to true on ordinal scales.
`roundDomains` only applies to linear scales.
No

fix(line-chart): only round linear scales, Fixes #254

---

src/bubble-chart/bubble-series.component.ts

Bugfix
Dates in tools tips are not properly formatted.
Dates in tools tips are now properly formatted.
No

fix(bubble): format dates in tooltips

---

demo/app.component.html
docs/charts/number-card.md
src/bar-chart/bar.component.ts
src/common/shape.helper.ts
src/number-card/card-series.component.ts
src/number-card/card.component.ts
src/number-card/number-card.component.ts

- Bugfix
Bands in number cards are rounded on all four corners.
Default card spacing is too tight.
Bands in number cards are rounded only on bottom corners.
Increased default card spacing.
Yes
Visual only.

fix(number-cards): Card bands should be only rounded on bottom

---

src/common/grid-layout.helper.ts

**What kind of change does this PR introduce?**
**What is the current behavior?** 
Pie grids with a total of 0 show `NaN%`: https://github.com/swimlane/ngx-charts/issues/286
If the pie grid total is 0, show `0%`.

If the total is 0, return 0 as the percent

---

src/pie-chart/pie-chart.component.scss
src/pie-chart/pie-label.component.ts

Pie chart labels use the d3 selection and transition APIs.
CSS animations are now used.  IE browsers do not support CSS transforms with SVG; as a result the existing visual behavior is maintained for IE.  Safari has a bug which prevents a CSS transform of a text element from being updated properly.  A group is introduced around the text element to allow the transforms to function.  Also, currently only Chrome supports transition animations of the `d` attribute; allowing Chrome the best visual experience.  However, other browsers fallback to existing visual behavior. …

refactor(pie-chart): use CSS animations for labels

---

demo/app.component.html
demo/app.component.ts
demo/chartTypes.ts
docs/charts/heat-map.md
src/heat-map/heat-map-cell-series.component.ts
src/heat-map/heat-map.component.ts

Feature
Demo
Heat map now supports `tooltipText` and `scaleType` as inputs.
Added heat map - calendar demo:
No

feature(heatmap): More heatmap options and calendar example

---

demo/app.component.html
src/heat-map/heat-map.component.ts

**What kind of change does this PR introduce?**
Feature
`innerPadding` only supports numbers and arrays of numbers as inputs.
`innerPadding` supports the following inputs:
Numbers: `8`
Strings: `"8"`, `"8px"`, `"8%"`
Arrays: `[8,2]`, `"8,2"`, `"[8,2]"`
Mixed: `[8,"2%"]`, `["8px","2%"]`, `"8,2%"`, `"[8,2%]"`
If no unit is given assumes `px`.
No
If this approach looks good I can apply to other charts as well.

feature(heat-map): support various inputs for innerPadding

---

src/common/base-chart.component.ts

At this time, only value, name and series fields of data entries are copied, so if you need more data to retrieve ie on select event can't get it.
In the series type of chart, is a side effect of the "Object.assign({}, seriesItem);" used to copy the series.
Now you can pass an "extra" data object to retrieve on chart events

Add "extra" field to cloneData() items 

---

config/webpack.package.js

@angular/animations was being bundled in the release output.
No longer bundled.
A patch release may be warranted as this could cause build issues for users of the package.

fix: don't bundle @angular/animations

---

src/bar-chart/bar-horizontal-2d.component.ts
src/bar-chart/bar-horizontal-normalized.component.ts
src/bar-chart/bar-horizontal-stacked.component.ts
src/bar-chart/bar-horizontal.component.ts

to match legend and input.
Bugfix
Horizontal bar charts have bars positioned in an order inverse of the domain input and the legend.
Horizontal bar charts should have bars positioned in an order matching the domain input and the legend.
Yes?
User land charts will reverse order.

Invert y-axis on horizontal bar charts

---

demo/app.component.html
demo/app.component.ts
src/line-chart/line-chart.component.ts

Takes care of #319 
- For line-chart, a new template option `showSeriesOnHover` has been added which can be set as true/false. 
- If set as `false`, all the data points on line will *not* be highlighted on hovering. This will stop the action which happens in case of current behavior where on hover, it adds all the line items to `activeEntries` and highlights all the g tags for that line which can become a performance hit in case of bigger data set.
- Default is `true`.

feature: added option in line-chart for disabling series on hover

---

src/area-chart/area-chart-normalized.component.ts
src/area-chart/area-chart-stacked.component.ts
src/area-chart/area-chart.component.ts
src/bar-chart/bar-horizontal-2d.component.ts
src/bar-chart/bar-horizontal-normalized.component.ts
src/bar-chart/bar-horizontal-stacked.component.ts
src/bar-chart/bar-horizontal.component.ts
src/bar-chart/bar-vertical-2d.component.ts
src/bar-chart/bar-vertical-normalized.component.ts
src/bar-chart/bar-vertical-stacked.component.ts
src/bar-chart/bar-vertical.component.ts
src/bubble-chart/bubble-chart.component.ts
src/common/charts/chart.component.ts
src/force-directed-graph/force-directed-graph.component.ts
src/gauge/gauge.component.ts
src/heat-map/heat-map.component.ts
src/line-chart/line-chart.component.ts
src/pie-chart/pie-chart.component.ts

Custom legend title not allowed. Open issue [#290](https://github.com/swimlane/ngx-charts/issues/290).
Legend title is configurable via an input on chart component.

feature: added an input for custom legend title

---

demo/app.component.ts
src/bubble-chart/bubble-chart.component.ts
src/common/base-chart.component.scss
src/common/trim-label.helper.ts

Bugfix
Tick labels with white space are not properly trimmed.  Some labels are cut off by clipping of SVGs.
Tick labels with white space are properly trimmed.  SVGs are no longer clipped.
No

fix(charts): fix label trimming and clipped svgs

---

package.json

Bugfix
@angular/http is a peer of ngx-ui, not installed by by ngx-charts
@angular/http is a peer of ngx-ui, now installed by by ngx-charts
No

fix: @angular/http is a peer of ngx-ui

---

src/number-card/card-series.component.ts
src/number-card/number-card.component.ts
src/utils/color-utils.ts

Bugfix
The invertColor helper fails if color is not a hex value or if opacity is zero.
Now using d3.color to get rgb color before inversion.
No

fix(number-cards): allow inverted colors from rgba values, fixed #365

---

src/gauge/gauge-arc.component.ts
src/gauge/gauge.component.ts

Fixes https://github.com/swimlane/ngx-charts/issues/362 by adding an explicit "any" type for the value parameter in the valueFormatter input.
Compiling with --noImplicitAny works.

fix(gauge): Add explicit "any" type declaration.

---

src/common/charts/chart.component.ts

The legend on a line-chart component is misplaced on the bottom of the chart on some resolutions. Rounding errors on the `legendWidth` are the issue here.
Fixes: #360
Truncate `chartWidth` and `legendWidth` instead of rounding it.

fix(legend): trauncate to get integers, fixes #360

---

demo/app.component.ts
demo/chartTypes.ts

Demo
Default options are now set per chart type in `chartTypes.ts`.
No
Will likely need to be rebased after PR #380.

Override defaults per chart type, based on chartTypes.ts

---

demo/app.component.html
src/number-card/card.component.scss
src/number-card/number-card.component.ts

Feature
Number cards show a "click" pointer even if no select listeners are attached.
Number cards only show a "click" pointer even if no select listeners are attached.
No

feature(number-cards): disable pointer if no click events are attached

---

release/gauge/gauge-arc.component.d.ts
release/gauge/gauge.component.d.ts

What kind of change does this PR introduce? (check one with "x")
What is the current behavior? (You can also link to an open issue here)
Error in [at-loader] valueFormatting parameter 'value' implicitly has an 'any' type in .
What is the new behavior?
No error and valueFormatting ’value’ parameter is declared ‘any’ type.
Does this PR introduce a breaking change? (check one with "x")
No

Fix Gauge: add type to valueFormatting parameter (#335)

---

src/utils/color-utils.ts

Bugfix
Importing a type from `@types/d3-color` causes errors.
Removed type importing, using `any`.
No

fix(color-utils): remove RGBColor type from util file

---

src/bar-chart/series-horizontal.component.ts
src/bar-chart/series-vertical.component.ts
src/line-chart/line-chart.component.ts

Takes care of #414. This implementation will take care of not creating tooltip svgs in case tooltips are set as false. This has been implemented for all the Bar Charts & Line chart.
- Modified Bar & Line Chart implementation to **NOT** to trigger tooltip creation in case of `tooltipDisabled`.
- Usage in demo/app.html stays the same, internal implementation is modified.

Feature: Disable tooltip tag creation in case of tooltipDisabled

---

package.json

Close #477
Removed patch numbers from peer dependencies in order to make them more lenient.
**What is the current behaviour?** (You can also link to an open issue here)
Currently these strict peer dependencies make it difficult for consumers who may be locked to specific versions of the dependencies. 
**What is the new behaviour?**
NPM resolution is more lenient, less warnings, and shrinkwrap doesn't break in npm `4.6.x`. 

Remove patch numbers from peerDependencies

---

src/common/tooltip/tooltip.component.ts
src/force-directed-graph/force-directed-graph.component.ts

`ngOutletContext` is being used. It is deprecated since angular v4 and will be removed in angular v5.
`ngOutletContext` is renamed to `ngTemplateOutletContext`.

(fix): Rename ngOutletContext (deprecated) to ngTemplateOutletContext

---

src/bubble-chart/bubble-series.component.ts

- [ x] Feature
Default tooltip has access to x and y value of a circle in the bubble chart. However, the context of a custom template has not.
The context of a custom tooltip template contains also x value.
- [x ] No

Added x-axis value to the context of a bubble chart tooltip.

---

src/common/svg-radial-gradient.component.ts

Bugfix
If the color input to a pie chart changes and the chart uses gradients, the colors are not updated.
Colors are now updated.
No

Fix(pie): Update pie chart gradients on color changes

---

docs/charts/area-chart-stacked.md
docs/charts/area-chart.md
docs/charts/bar-horizontal-2d.md
docs/charts/bar-horizontal-stacked.md
docs/charts/bar-horizontal.md
docs/charts/bar-vertical-2d.md
docs/charts/bar-vertical-stacked.md
docs/charts/bar-vertical.md
docs/charts/bubble-chart.md
docs/charts/line-chart.md
docs/charts/polar-chart.md
src/area-chart/area-chart-stacked.component.ts
src/area-chart/area-chart.component.ts
src/bar-chart/bar-horizontal-2d.component.ts
src/bar-chart/bar-horizontal-stacked.component.ts
src/bar-chart/bar-horizontal.component.ts
src/bar-chart/bar-vertical-2d.component.ts
src/bar-chart/bar-vertical-stacked.component.ts
src/bar-chart/bar-vertical.component.ts
src/bubble-chart/bubble-chart.component.ts
src/bubble-chart/bubble-chart.utils.ts
src/line-chart/line-chart.component.ts
src/polar-chart/polar-chart.component.ts

Fixes: #228 
This PR adds `xAxisMinScale` and `yAxisMinScale` where possible to force axis scaling to the provided value.
If the provided value is smaller than one of the chart data values, it is ignored and axis scaling will use chart data as usual.
Some `xAxisMinScale` and `yAxisMinScale` definitions are set to `any` on purpose, to allow adding dates when using time scale types.
Following chart types have been extended with this feature:
- Vertical Bar Chart
- Horizontal Bar Chart
- Grouped Vertical Bar Chart
- Grouped Horizontal Bar Chart
- Stacked Vertical Bar Chart
- Stacked Horizontal Bar Chart
- Area Chart
- Stacked Area Chart
- Line Chart
- Bubble Chart
- **Polar Chart** (added …

feat(charts): force minimum axis scale

---

src/area-chart/area-chart-normalized.component.ts
src/area-chart/area-chart-stacked.component.ts
src/area-chart/area-chart.component.ts
src/line-chart/line-chart.component.ts

This fixes an issue where the tooltip would not appear for certain data
points. I had thirty data points in a line chart, and the tooltip was
working for points 1 and 10, but 2-9 were being skipped over. Looking
further, I noticed that the array of points along the x axis was not being
sorted in the correct order. The numbers were being sorted in
alphabetical order (which explains why 10 came after 1), so I added a
compare function in the related sorts to sort the numbers in xSet
numerically.
When using a line chart or are chart with the linear scale type, if there are
more than 10 data points, the tooltip will not appear for certain points. …

Fix bug: Tooltip not appearing for certain points

---

src/gauge/gauge.component.ts

- [ x] Bugfix
The gauge arc animation restarts from zero on every update
The gauge arc animation updates correctly
- [ x] No

(fix): Do not restart value arc animation on update

---

src/polyfills.ts

Fixes an exception that happens when launching Universal Server.
```
npm info lifecycle p4-monitor-angular@0.0.0~postbuild:universal:server: p4-monitor-angular@0.0.0
npm info ok
npm info lifecycle p4-monitor-angular@0.0.0~postbuild:universal:prod: p4-monitor-angular@0.0.0
npm info ok
/workdir/p4-monitor-angular/dist/server/server.js:157204
if (typeof SVGElement.prototype.contains === 'undefined') {
^
ReferenceError: SVGElement is not defined
at Object.defineProperty.value (/workdir/p4-monitor-angular/dist/server/server.js:157204:12)
at __webpack_require__ (/workdir/p4-monitor-angular/dist/server/server.js:20:30)
at Object.SVGElement.contains (/workdir/p4-monitor-angular/dist/server/server.js:157141:69)
at __webpack_require__ (/workdir/p4-monitor-angular/dist/server/server.js:20:30)
at …
```

Bugfix exception when launching Universal Server

---

src/polyfills.ts

AoT build fails with:
```
ERROR in TypeError: Cannot read property 'version' of null
at readMetadataFile (/Users/ez/Github/highland-ui/node_modules/@angular/compiler-cli/src/transformers/metadata_reader.js:66:29)...
```
AoT build succeeds.
Closes #639

(fix): Export polyfills to fix AoT build issue with Angular 5

---

src/area-chart/area-chart-normalized.component.ts
src/area-chart/area-chart-stacked.component.ts
src/area-chart/area-chart.component.ts
src/line-chart/line-chart.component.ts

Timeline doesn't show unless scaleType is 'time'.
Timeline is shown when scaleType is not 'ordinal' (i.e. when scaleType is 'time' or 'linear'). 

Disable timeline only on 'ordinal' scale type (#624)

---

src/common/base-chart.component.ts
tslint.json

ngx-charts uses patch rxjs operators #682
ngx-charts uses lettable rxjs operators
This PR also disallows importing the entire rxjs operators library for better tree-shaking.

Use lettable rxjs operators

---

docs/charts/advanced-pie-chart.md
src/common/legend/advanced-legend.component.spec.ts
src/common/legend/advanced-legend.component.ts
src/pie-chart/advanced-pie-chart.component.ts

Added to be used in the advanced pie chart component.
Should help with #201
Currently, the formatting for values in the legend cannot be formatted by a client of the api. This helped bring up the issue seen in #201 
It is possible to provide a formatter function for the name, value, and percentage properties of the legend.
The existing behavior remains unchanged.

(feat): Added options for formatting the name, value and percentage values in the advanced legend component

---

src/common/tooltip-area.component.ts

Solves #469. 
event.pageX - event.target.getBoundingClientRect().left gives me a different value then event.offsetX as where as in Firefox and IE these two result in exactly the same numbers. The difference between the numbers in Chrome is compensated by subtracting this.dims.xOffset. 
To make this work in all browsers we could just use
const xPos = event.pageX - event.target.getBoundingClientRect().left; instead of using offsetX and subtracting it with dims.xOffset.
See #469 
posX is now cross browser always the same.
If this PR contains a breaking …

Fix for wrongly positioned tooltip

---

src/pie-chart/pie-label.component.ts

Label on pie charts trim at 10 characters and there's no way of changing this
Labels on pie charts can now be configured to not trim, or a custom trim length. Omission of either results in 10 characters trimming as is current behavior.
Much needed, label trimming is annoying when it's fixed and can't be changed!
As per the [comment here](https://github.com/swimlane/ngx-charts/issues/337#issuecomment-295380159)
> There is not one at the moment. The reason for that is that we have an algorithm which positions the labels in a way …

(feat): Allow configuration of label trimming on pie chart

---

src/common/shape.helper.ts

Bugfix
If a bar chart has many values the height (or width) of the bar can become <1px, resulting in an invalid path.
Bars have a minimum height and width of 1px.
No

Avoid invalid paths when rect shape has 0 width or height

---

src/common/circle-series.component.ts

Removed circles array, as it was not used outside the component, which resulted in opportunity to speed this process up.
Current behaviour, with large graphs, the performance was getting a bit sluggy.
I've tested this with 5 lines, 5000 datapoints, with lince-chart component.
When hovering over the chart, it resulted in a average frametime of 1000ms.
Old behaviour, was mapping all circles, and then selecting the correct one.
New behaviour is first finding the index of the correct one, and then map that datapoint to a circle object.
New average frametimes when hovering are around 550ms for this dataset.
So for this …

Perf improvement CircleSeriesComponent

---

src/common/axes/x-axis-ticks.component.ts
src/common/axes/x-axis.component.ts
src/line-chart/line-chart.component.ts

- [ x ] Feature
This adds the feature described in #718. Before this fix you could not specify custom x-axis-ticks for a line chart.
You can now use the xAxisTicks input to pass an array of the ticks you would like used.
- [ x ] No

Feature xaxis ticks

---

src/area-chart/area-chart.component.ts
src/area-chart/area-series.component.ts

The purpose of this option is to provide an area chart
which start from a specific floor value and can handle reverse areas.
Instead of starting the area from the lowest value of all series,
if a serie contains values inferior to the floor value,
it will display a reverse area with a "negative" spike.
The current behaviour always start areas from the lowest values of all series.
Areas can (optional) start from a specific floor value, which can display negative spikes and reverse areas.
I opened an issue [here](https://github.com/swimlane/ngx-charts/issues/681) before making this PR.
Example : …

Handle area charts based on a specific floor value

---

demo/sparkline/sparkline.component.ts
src/area-chart/area-chart-normalized.component.ts
src/area-chart/area-chart-stacked.component.ts
src/area-chart/area-chart.component.ts
src/common/base-chart.component.ts
src/common/domain.helper.ts
src/line-chart/line-chart.component.ts

Another one coming in. :)
Converted to using sets instead of includes on possible large data.
Tackles #714 and maybe #519, but not completely.
For the usecase (2 lines, 30k datapoints) duration went from 600ms to 80ms, the function gets called 4 times, so it makes a difference, but it still takes a bit of time to load this graph.
With 100 points, the performance is about equal, below 100 datapoints, old scenario is faster.
But we are talking about overhead of going from set --> array, which in category of a 0.00x ms differences on my machine.
It just makes ngx-charts a bit more scalable/useable with larger data (>100 datapoints).
Using …

Performance improvement, (various charts, large data)

---

src/common/axes/x-axis-ticks.component.ts

Use the tick formating function to compute the X axis ticks angle.
We are using our own X tick formatting function which reduces a date to "month/day" format, but the actual code does not use this function to compute the x axis tick angle. In our case, the tick text should not be rotated but the current implementation produces an angle of -30 or -60 deg instead.
Moreover, as a side effect, we are seeing a flickering of the line chart, as the angle changes between -30 and -60 deg continuously.
The x axis tick angle is computed accordingly to the tick string displayed. …

Fix computation of X axis ticks angle

---

docs/examples/polar-radar-chart.md
src/polar-chart/polar-chart.component.ts

Label on polar charts trim at 10 characters and there's no way of changing this #857 
Labels on polar charts can now be configured to not trim, or a custom trim length. Omission of either results in 10 characters trimming as is current behavior.
Closes #857

(feat): Allow configuration of label trimming on polar chart

---

src/line-chart/line-series.component.ts

**What kind of change does this PR introduce?** 
**What is the current behavior?** 
https://github.com/swimlane/ngx-charts/issues/853
if `.line-heightlight` area is visible not only with user hover then it doesn't animate is there is no corresponding property on `line-series` component
**Does this PR introduce a breaking change?** 

use animations for line-highlight depending on line-series animations

---

demo/app.component.html
demo/app.component.ts
demo/chartTypes.ts
src/heat-map/heat-map.component.ts

- [ x] Feature
this is a PR for https://github.com/swimlane/ngx-charts/issues/602
previously there was no way to set min and max values for heatmaps 
you can set the min as well as max for heatmap if not provided they will be calculated as before from the given data
- [x ] No
I'm eager to get this merged so will do the required changes if any asap

Ability to set Min and Max values for heatmaps closes #602

---

src/common/tooltip/injection.service.ts

Feature
Allows the app to define a global root view container that will be used by all tooltip instances.
No

setGlobalRootViewContainer

---

src/common/legend/advanced-legend.component.ts

https://github.com/swimlane/ngx-charts/issues/865
Fix for the above issue. Just save the value before it's formatted and use that instead of a potential string in countTo

save preformatted version of value so that countTo doesn't produce NaN

---

demo/app.component.html
demo/app.component.ts
src/common/legend/advanced-legend.component.ts

Value formatting (e.g. adding a currency symbol) does not work for legend of ngx-charts-advanced-pie-chart if animations are enabled (see issue #865) and is not applied to its total value (see issue #794). 
Value formatting works on values and total value with and without animations enabled.

Fix value formatting for advanced-legend

---

src/common/legend/advanced-legend.component.scss
src/common/legend/advanced-legend.component.ts

Colors are missing in advanced-legend when printing charts (see issue #784) because browsers ignore the css property background-color when printing.
By using a border instead of background-color for displaying colors in the legend these are now also shown in print. This fix works at least for Chrome 67 and Firefox 61 and it should also work for other browsers but I haven't tried it.

Fix advanced-legend colors in print

---

src/common/index.ts

A user pointed out that the domain.helper function is not being exported in [this issue](https://github.com/swimlane/ngx-charts/issues/882)

Added export for domain.helper

---

README.md

Replaced: https://github.com/swimlane/ngx-charts/blob/master/docs/intro/custom-charts.md
With: https://github.com/swimlane/ngx-charts/blob/master/docs/custom-charts.md
Current link to the Custom Charts Page doesn't resolve properly.
Link resolves to the correct URL.

Fixed Custom Charts Page link in README.md

---

src/common/circle-series.component.ts

Fixes #855
- Bugfix
There is a typo in imports and it's fixed in this PR.
See #855 for more detail.
- No
This issue prevents us from using this library, as it fails when Angular Server Side Rendering feature is used.
P.S. The unit test reported by Travis was broken before my change.

Fix invalid ColorHelper type import

---

src/common/tooltip-area.component.ts
src/events.ts
src/force-directed-graph/force-directed-graph.component.ts
src/pie-chart/pie-arc.component.ts

Node doesn't contain `MouseEvent` type definition and package fails if is imported by the Angular Server Side Rendering module. Here we add a workaround and import MouseEvent type from the place where it exists.
Fixes #460 Fixes #572 
- Bugfix
See #460 for more detail
- No
This issue prevents us from using this library, as it fails when Angular Server Side Rendering feature is used. It's a critical one for us 😟 
I tried to copy `events.ts` without changes from here:
https://github.com/swimlane/ngx-datatable/blob/7b0d6359fd0298f726eb15dabc392cef1c2dc2a6/src/events.ts#L4
However, it fails …

Add MouseEvent workaround for the Server Side Rendering

---

src/area-chart/area-chart.module.ts
src/bar-chart/bar-chart.module.ts
src/bubble-chart/bubble-chart.module.ts
src/force-directed-graph/force-directed-graph.module.ts
src/gauge/gauge.module.ts
src/heat-map/heat-map.module.ts
src/line-chart/line-chart.module.ts
src/number-card/number-card.module.ts
src/pie-chart/index.ts
src/pie-chart/pie-chart.module.ts
src/polar-chart/polar-chart.module.ts
src/tree-map/tree-map.module.ts

Currently all the components are exported twice:
- via `index.ts` files
- via `module.ts` files
Components are exported only once, via `index.ts` files. That's the common angular package behavior to export components via the `index.ts` or `public_api.ts` files.
This issue causes errors when used with Server Side Rendering and is preventing us from using the package.
**Scenario:**
- Install package.
- Apply workaround described [here](https://github.com/swimlane/ngx-charts/issues/18#issuecomment-405571689).
- Run application with SSR enabled.
**Result:** Angular fails …

Remove duplicated exports

---

src/bar-chart/bar-label.component.ts
src/bar-chart/index.ts
src/bubble-chart/index.ts
src/gauge/index.ts
src/pie-chart/index.ts

add missing exports to index.ts in bar-chart, bubble-chart, gauge, pie-chart
also, correct an import of formatLabel in bar-label.component which was causing rollup bundling to fail
- [x ] Bugfix
restores some exports missing since this [PR](https://github.com/swimlane/ngx-charts/pull/919)
- [ x] No

add missing exports

---

package.json

Move d3 libraries back to regular ol' dependencies to preserve ease of install

Move d3 libraries back to dependencies

---

src/bar-chart/bar.component.ts
src/bar-chart/series-horizontal.component.ts
src/bar-chart/series-vertical.component.ts

- [x ] Feature
When tabbing to the first bar in the bar graph chart, JAWS screen reader reads the highest y-axis value in the page instead of the value of the currently focused bar. It again repeats this same value for all bars in the chart.
When tabbing to the first bar in the bar graph chart, JAWS screen reader reads the value of the currently selected bar, not the highest value in the graph. This behavior would be consistent with every bar in the table.
- [x ] No
If this PR contains a breaking change, please describe the impact and migration path …

Added accessibility attributes to bar charts

---

src/pie-chart/pie-series.component.ts

Positioning of labels in Pie-charts sometimes places the labels outside of the container.
This has been reported in #844 
The issue mentioned above has been fixed with version 8.0.2, see [here](https://github.com/swimlane/ngx-charts/commit/2568a4b7f36802d6bc98e42e31e0b90edac691e9).
But ngx-charts version 8.0 introduced a breaking change in depending on Angular 6!
This pull request introduces the necessary changes for the 7.x branch, so that users who have to continue working with Angluar 5 (and thus ngx-charts < 8) can also use correctly aligned labels.
Would be great if this could become ngx-charts v7.4.1
**Does …

fix: pie chart label positioning for 7.x branch

---

demo/combo-chart/combo-chart.component.ts

The clip-path binding is not used in this component, there is no matching property in the typescript
The demo Combo Chart component contains an unused property binding.
The unused binding has been removed.

Remove unused property binding from demo chart

---

src/tree-map/tree-map-cell.component.ts
src/tree-map/tree-map.component.scss

foreignObject uses the label class that can conflict with other libraries.
```
<foreignObject class="label ng-star-inserted" x="0" y="0" width="364.15491003825497" height="151" style="pointer-events: none;"><p style="color: rgb(216, 226, 235); height: 151px; width: 364.155px;"><span class="treemap-label">Google</span><br><span class="treemap-val ng-star-inserted" ngx-charts-count-up="">10.2 TB</span></p></foreignObject>
```
changed the label class to treemap-label to avoid conflicts.
If this PR contains a breaking change, please describe the impact …

Changed tree-map label class to avoid conflict

---

demo/combo-chart/combo-chart.component.ts
src/bar-chart/bar-vertical.component.ts

As mentioned in the issue: https://github.com/swimlane/ngx-charts/issues/728
If we have many variables (more than 50) in the `results`  of `bar-chart` or `combo-chart`, there will be too much spacing around the left and right of the `bar-chart`, resulting the line and bar not aligning in the `combo-chart`.
set the `results` of `bar-chart` or `combo-chart` to be (180 variables)
```
[{ time: 1556612978, name: '16:29:38', value: 180 }, { time: 1556613018, name: '16:30:18', value: 145 }, { time: 1556613058, name: '16:30:58', value: 144 }, { time: 1556613098, name: '16:31:38', value: 144 }, { time: 1556613138, name: '16:32:18', value: 144 }, { time: …
```

Combo Line and Bar chart not aligning

---

src/common/base-chart.component.ts
src/common/charts/chart.component.ts
src/common/view-dimensions.helper.ts
src/polar-chart/polar-chart.component.ts

There is an inconsistent use of using bitwise operators (~~) and Math.floor() to round numbers down.
A consistent usage of Math.floor() rather than ~~.
**Other information**:  
While in some browsers using ~~ to floor a variable can be faster than Math.floor() it isn't consistently faster between browsers or even browser versions. As Math.floor() is more readable it seems preferable.

Replace bitwise operator ~~ with math.floor

---

src/common/tooltip/position/position.spec.ts
src/common/tooltip/position/position.ts
src/common/tooltip/tooltip.component.ts

[Open Issue](https://github.com/swimlane/ngx-charts/issues/1081)
The issue can also be observed on the [demo page line chart](https://swimlane.github.io/ngx-charts/#/ngx-charts/line-chart) by setting your browser width to 788px and observing the final two series tooltips
The positioning check is now independent of alignment and will correctly determine if there is enough available space.
I wasn't sure how to mark this, but I chose "Yes" because I removed an input parameter. If someone were importing the PositionHelper directly, this would break for …

Update tooltip positioning to correctly flip sides when there is not enough available space

---

src/common/chart-common.module.ts

The hardcoded PathLocationStrategy changes the routing behavior of Angular
applications. This causes issues, as it potentially overwrites the intended
routing strategy. This is especially problematic for lazy loaded modules, where
the proposed workaround (reordering of modules) doesn't work. In those cases,
an ugly hack is needed that sets the location strategy explicitely in every
lazy loaded module.
For more information, see https://github.com/swimlane/ngx-charts/issues/601
Please keep in mind, that this change may break existing applications, that
unknowingly rely on the "pre-configured" location strategy provided by
ngx-charts. In case this pull request gets merged, at least a notice should
be left in the documentation / change logs / github page.
**What kind of change does this PR …

Remove Angular location strategy from ChartCommonModule

---

package.json

Resolving the issue where running 'yarn' will complain about unmet peer dependencies (which are already resolved in devDependencies)
NPM/Yarn warns unmet peerDependencies when they are already resolved in devDependencies. https://github.com/swimlane/ngx-charts/issues/1032
Just resolve libs in devDependencies

Removing duplicative and unnecessary peer dependencies (#1032)

---

src/pie-chart/pie-chart.component.ts

Margins in the pie chart component have a hard coded value. When no label/legend for the chart is set, these margins take up unnecessary space. In our case we can't even make the component fit into the lower part of the specific page where we want to use the chart.
The pie chart component now has an `@Input` field for margins. If desired, this field can be set. If it is not set or empty, there are two possibilities:
+ `labels` is set (and `margins` either unset or empty) -> `margins` will be set to `[30, 80, 30, 80]`, as it was previously the case.
+ `labels` is not set (and `margins` either unset or empty) -> `margins` will be set to `[20, 20, 20, 20]`, as …

Make margins optional for pie chart component

---

src/common/color.helper.ts

If value is null, this method fails with an error. This makes it easier for a developer to track down the issue at hand.
- [X ] Bugfix
Fails with a generic error, making it harder to track down the issue. I encountered this issue when one of my nodes' labels came in as undefined. 
Throw a more verbose error making it easier to track down why the issue is occuring. 

Update Color.Helper.ts to handle null values

---

README.md
demo/app.component.html
demo/chartTypes.ts
docs/features.md

A while back, we saw the need for a more advanced library to visualise graph data in angular. The force-directed chart did that, but in a limited way and was lacking features, so we decided to build a better graph visualisation component.
Additionally, graph visualisation is a huge field on its own, so we felt it would be better to split the component into its own package, so we created [@swimlane/ngx-graph](https://github.com/swimlane/ngx-graph)
In ngx-graph v6, we added the option for customisable graph layout, so now it can do everything that the force-directed chart does, and much more. 
This is why we are deprecating the force-directed chart, and recommend replacing it with @swimlane/ngx-graph instead. 
The …

Deprecate force-directed graph chart

---

src/bar-chart/bar-vertical.component.ts

When specify `yAxisTicks`, if the max y tick is larger than the max yvalue of data and the `yScaleMax` data, then the inner `g` will exceed the height limit. The workaround is to set the `yScaleMax` larger equal then the largest value of `yAxisTicks`, but feel we should document somewhere.
In the meanwhile, open this POC PR to see if this fix is right on track and hope to got reviewed. The existing graph looks like (max height 300px):
Max height:300px
If this PR contains a breaking change, please describe the impact and migration path for existing …

Fix chart height with large number of yAxisTicks, just a Poc for further feedback to go or not

---

demo/combo-chart/combo-chart.component.ts

The bar chart in the combo chart always uses the integer width of the bar and in case of a large domain, it can contain additional offsets by sides. But the line chart doesn't take these offsets.
Now the `getXScaleLine` call has calculated the offset of the bar chart and used it for correction of the line chart. The updating of the bar width is calling the scaling of the line chart also.

Fix line chart scaling on combo charts with large domain

---

src/bar-chart/bar-vertical-stacked.component.ts

Getting a console error when using `BarVerticalStackedComponent`.
Error is gone after defaulting to `0` if `xScale()` returns undefined.

checkout for undefined xScale in groupTransform

---

projects/swimlane/ngx-charts/src/lib/common/tooltip/tooltip.directive.ts

#511 
Tap or long press on bar chart does not display a tooltip. A long press shows an unpopulated tooltip with incorrect css applied.
Tap on any chart bar (or pie slice) should display tooltip.

(fix): Chart Tooltip does not work on touch devices

---

projects/swimlane/ngx-charts/src/public-api.ts

missing api import:
export * from './lib/common/tooltip/position/placement.type';
can't import PlacementTypes from tooltip position in order to use it in a combo chart with typescript strict checking enabled
you can import PlacementTypes

added placement.type in public-api.ts

---

docs/changelog.md
package-lock.json
package.json
projects/swimlane/ngx-charts/package.json
projects/swimlane/ngx-charts/src/lib/area-chart/area-chart.component.ts
projects/swimlane/ngx-charts/src/lib/pie-chart/pie-label.component.ts

* d3-shape was not included as a dep in the released package
* ngx-charts was using an incorrect type for curves
* @types/d3-shape is now a dependecy
* now using correct type for curves

fix d3-shape typing and package

---

projects/swimlane/ngx-charts/src/lib/common/area.component.ts

Line charts display a gray solid fill instead of a colored gradient when additional series are added to the input "results" as shown in #1158 and demonstrated by this [stackblitz](https://stackblitz.com/edit/ngx-charts-line-chart-bug?file=src/app/app.component.ts).
https://user-images.githubusercontent.com/2646053/121236148-a0cc6780-c863-11eb-9275-d0eb0ccb1f5a.mov
Line charts show a colored gradient as demonstrated by this [stackblitz](https://stackblitz.com/edit/ngx-charts-line-chart-fix)
https://user-images.githubusercontent.com/2646053/121545929-ef4f4280-c9d8-11eb-86e8-35d182e9dbf7.mov
**Does this PR introduce a …

Fixes #1562 #1165 #1158 #1062 #808 #672

---

angular.json
projects/swimlane/ngx-charts/ng-package.json

Currently, there are warnings when building the demo app with `npm run build:demo`.
```bash
> npm run build:demo
> ngx-charts@0.0.0 build:demo /home/runner/work/ngx-charts/ngx-charts
> npm run build:lib:prod && cross-env NODE_ENV=production ng build --configuration production --base-href="/ngx-charts/"
> ngx-charts@0.0.0 build:lib:prod /home/runner/work/ngx-charts/ngx-charts
> ng build @swimlane/ngx-charts --configuration production
Building Angular Package
❗👀 WARNING: Option "whitelistedNonPeerDependencies" is deprecated: Use "allowedNonPeerDependencies" instead.
- Compiling with Angular in legacy View Engine compilation mode. …
```

fix: warnings when `npm run build:demo`

---

projects/swimlane/ngx-charts/src/lib/common/base-chart.component.scss
projects/swimlane/ngx-charts/src/lib/heat-map/heat-map-cell.component.ts
projects/swimlane/ngx-charts/src/lib/tree-map/tree-map-cell.component.ts

- `cursor: pointer` style was directly set on the element
- `!important` is needed if one would like to change this style
- cursor style is set via css and therefore follows the pattern which is also used for e.g. `.bar`
- this allows to target `.cell` without using `!important`

refactor: remove element-style on heat-map-cell

---

projects/swimlane/ngx-charts/src/lib/common/tooltip/tooltip.directive.ts

Modify timeout time from 300 to 400 on iOS
fixes [#1228](https://github.com/swimlane/ngx-charts/issues/1228)
- [X ] Bugfix
Tooltips don't display in various chart types on iOS devices (e.g, bar chart)
Tooltips do display on iOS devices
- [ X] No

change ios timeout

---

projects/swimlane/ngx-charts/src/lib/common/charts/chart.component.ts

https://github.com/swimlane/ngx-charts/issues/1181
Linear chart is not setting a correct value for height because the value retrieved for getContainerDims is not correct
Setting the height for the container element in the html template
Other tests to ensure all charts are working

Setting height for container

---

package-lock.json
package.json
projects/swimlane/ngx-charts/package.json
projects/swimlane/ngx-charts/src/lib/common/base-chart.component.scss
projects/swimlane/ngx-charts/src/lib/common/base-chart.component.ts
projects/swimlane/ngx-charts/src/lib/models/chart-data.model.ts
projects/swimlane/ngx-charts/src/lib/ngx-charts.module.ts
projects/swimlane/ngx-charts/src/lib/sankey/sankey.component.spec.ts
projects/swimlane/ngx-charts/src/lib/sankey/sankey.component.ts
projects/swimlane/ngx-charts/src/lib/sankey/sankey.module.ts
projects/swimlane/ngx-charts/src/public-api.ts
src/app/app.component.html
src/app/app.component.ts
src/app/chartTypes.ts
src/app/data.ts

A new sankey diagram chart type is added

Sankey diagram

---

docs/changelog.md
package.json
projects/swimlane/ngx-charts/package.json
projects/swimlane/ngx-charts/src/lib/gauge/percent-gauge/percent-gauge.component.scss
projects/swimlane/ngx-charts/src/lib/gauge/percent-gauge/percent-gauge.component.ts
src/app/app.component.scss
yarn.lock

- Fixes server-side-rendering for Percent Gauge Chart
- Fixes light theme for Percent Gauge Chart
- Makes target circle highlight only when target is reached 

Percent gauge SSR

---

docs/changelog.md
projects/swimlane/ngx-charts/package.json
projects/swimlane/ngx-charts/src/lib/gauge/percent-gauge/percent-gauge.component.ts

- Circle masks are now unique per percent gauge chart used on the page

Use a unique mask ID for each percent gauge chart

---

README.md
projects/swimlane/ngx-charts/src/lib/bar-chart/bar-horizontal-2d.component.ts
projects/swimlane/ngx-charts/src/lib/bar-chart/bar-horizontal.component.ts
projects/swimlane/ngx-charts/src/lib/bar-chart/bar-vertical-stacked.component.ts
projects/swimlane/ngx-charts/src/lib/bar-chart/bar-vertical.component.ts
projects/swimlane/ngx-charts/src/lib/bar-chart/series-horizontal.component.ts
projects/swimlane/ngx-charts/src/lib/bar-chart/series-vertical.component.ts
projects/swimlane/ngx-charts/src/lib/box-chart/box-chart.component.ts
projects/swimlane/ngx-charts/src/lib/bubble-chart/bubble-chart.component.ts
projects/swimlane/ngx-charts/src/lib/gauge/gauge.component.ts
projects/swimlane/ngx-charts/src/lib/gauge/linear-gauge.component.ts
projects/swimlane/ngx-charts/src/lib/heat-map/heat-map.component.ts
projects/swimlane/ngx-charts/src/lib/line-chart/line-chart.component.ts
projects/swimlane/ngx-charts/src/lib/number-card/number-card.component.ts
projects/swimlane/ngx-charts/src/lib/pie-chart/advanced-pie-chart.component.ts
projects/swimlane/ngx-charts/src/lib/pie-chart/pie-chart.component.ts
projects/swimlane/ngx-charts/src/lib/pie-chart/pie-grid.component.ts
projects/swimlane/ngx-charts/src/lib/polar-chart/polar-chart.component.ts
projects/swimlane/ngx-charts/src/lib/sankey/sankey.component.ts
projects/swimlane/ngx-charts/src/lib/tree-map/tree-map.component.ts

With Angular 19, Chart Components are not receiving updates sometimes, especially when changing custom colors but when `ngOnChanges` is properly declared, the issue is resolved. This method was inherited before but due to some change in how Angular is compiled this no longer works. 
I also updated the README.md for making releases.
* fix: README.md
* fix: angular 19 may not trigger ngOnChanges

ngOnChanges not working
